### ISSUE TITLE
single-noticia - Assinatura e data + sociais

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#11]
Assinatura e data da postagem abaixo da foto destacada
como descrito em:
https://docs.google.com/document/d/12BHMajE__yUBomUqvGmvODMMXbmosWZrlSkNHdoQ-MI/edit

**Comment by isaquemelo** [comment]
Mano, temos um problema de UX se fizermos isso.. a informação subsequente à imagem dará a entender que a informação datada refere-se à imagem, já que ela já tem uma informação abaixo (crédito do fotografo e descrição). Em linhas gerais, as informações vão se misturar e vai ficar uma zona para o usuário entender.

**Comment by isaquemelo** [comment]
Outro detalhe a se lembrar é que a area do post header é toda centralizada o que não acontece abaixo que já é criado um novo padrão de alinhamento a esquerda para facilitar a leitura do usuario. Se deixarmos a informação referente ao post após à imagem ficaremos com uma ordem de alinhamento de texto assim:
 CENTRO (header)
 ESQUERDA (imagem - informação da imagem)
 CENTRO (informação do post - quebrando sequencia)
 ESQUERDA (corpo geral)

**Comment by willowmagrini** [comment]
OK, vou conversar com ele e depois retomamos aqui

**Comment by willowmagrini** [comment]
Vamos manter essa área centralizada mas ele quer tentar reduzir o tamanho que as informações do texto ocupam antes da foto (seta roxa na imagem).  o texto "modificado em..." vai sair dessa área, e eles querem testar colocar na mesma linha, à direita os icones sociais (serão acrescentados mais dois icones, instagram e imprimir) e à esquerda  informação do autor e data de publicação.
Acho que também podemos diminuir o tamanho do vazio acima do chapéu (seta laranja) 
![captura de tela 2018-03-14 as 23 20 31](https://user-images.githubusercontent.com/8497431/37441596-f9c413be-27e0-11e8-92c1-7a69af82e6e0.png)
