### ISSUE TITLE
single-noticia - Header

### ISSUE THREAD

**Issue by matheusgimenez** [brasadesign/esquerdaonline-theme#12]

**Comment by matheusgimenez** [comment]
Eu fiz o header, ainda sem algumas funcionalidades (como o menu hamburguer e a função de seguir na tela);

Minha ideia aqui é o @isaquemelo estilizar o que temos, pra podermos fazer a demonstração para o Gustavo hoje.

**Comment by isaquemelo** [comment]
@matheusgimenez falta fazer o form de search para eu poder colocar estilo.
