### ISSUE TITLE
single-noticia - Widget de taxonomia

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#17]
- "Movimentos" vira "brasil" (nome da editoria);
- O chapéu "brasil" desaparece;
- Adicionar link para o archive no final do widget .

**Comment by matheusgimenez** [comment]
Feito!

@isaquemelo da uma embelezada pra noiz quando puder, ok?

**Comment by isaquemelo** [comment]
Aqui só falta eu recolocar o botão e estilizar @willowmagrini.. Mais tarde faço isso
