### ISSUE TITLE
single-noticia - Sociais 

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#18]
Adicionar ícone do instagram e de imprimir na single

**Comment by matheusgimenez** [comment]
@isaquemelo consegue fazer esse? é só adicionar o icone de imprimir, deixa com o link vazio e dps eu adiciono a funcionalidade ok? Abs!

**Comment by isaquemelo** [comment]
Falta alguma coisa aqui @willowmagrini?

**Comment by willowmagrini** [comment]
nao

**Comment by willowmagrini** [comment]
@matheusgimenez Falta a funcionalidade nisso

**Comment by willowmagrini** [comment]
Tem o do topo e os da listagem no final da página

**Comment by willowmagrini** [comment]
Os icones da listagem abaixo do conteúdo estão compartilhando a noticia que esta aberta
