### ISSUE TITLE
Single noticias

### ISSUE THREAD

**Issue by matheusgimenez** [brasadesign/esquerdaonline-theme#2]
![single-page](https://user-images.githubusercontent.com/4724804/37071280-886940e6-219a-11e8-8d2a-e938f42bcfc6.png)

**Comment by matheusgimenez** [comment]
Exemplo de post com todos campos adicionados:

**Comment by matheusgimenez** [comment]
https://novodev.brasa.art.br/esquerdaonline/2017/08/12/municiparios-de-porto-alegre-mobilizados-para-derrotar-marchezan/

**Comment by matheusgimenez** [comment]
@isaquemelo Preciso que vc faça a sombra degradê da imagem destacada usando Blending Options do Photoshop, pq dai dá pra copiar o CSS disso ai..

Pode me mandar? Abs!

**Comment by isaquemelo** [comment]
@matheusgimenez O codigo esta bem sujo mano.. dá aquele trato


background-image: -moz-linear-gradient( 90deg, rgb(0,0,0) 0%, rgba(47,47,47,0.71) 29%, rgb(47,47,47) 100%);
  background-image: -webkit-linear-gradient( 90deg, rgb(0,0,0) 0%, rgba(47,47,47,0.71) 29%, rgb(47,47,47) 100%);
  background-image: -ms-linear-gradient( 90deg, rgb(0,0,0) 0%, rgba(47,47,47,0.71) 29%, rgb(47,47,47) 100%);
  opacity: 0.8;

**Comment by matheusgimenez** [comment]
@isaquemelo Nao consegui aplicar aqui.. mas enfim, deixo isso pra dps

**Comment by isaquemelo** [comment]
@matheusgimenez background: linear-gradient(rgba(255,255,255,0) 29%, rgba(191,191,191,0) 46%, rgba(0,0,0,0.78) 97%, rgba(0,0,0,0.8) 98%); gerei outro aqui.. se nao funcionar dá uma olhada ai

**Comment by matheusgimenez** [comment]
@isaquemelo Agora só preciso do tamanho da imagem destacada pra criar um image_size no WP.

**Comment by isaquemelo** [comment]
@matheusgimenez Mano o tamanho vai variar de tela para tela, a proporção pelos meus cálculos é 11:5.. No layout para telas largas isso dá 1100px por 500px

**Comment by matheusgimenez** [comment]
@isaquemelo Ta faltando nessa single a area de "meta", que seria mostrar as categorias, tags, que tiverem marcadas no post. Isso fica no final da materia.
Tem que pensar a area de coordenadorias, que seriam materias relacionadas, o visual de ambas as coisas podem ser iguais, a unica diferença eh que coordenadorias vai ser colocado no meio do post via shortcode

**Comment by willowmagrini** [comment]
Vou fechar essa porque abri issues mais específicas
