### ISSUE TITLE
Menu - Menu hamburguer

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#24]
@isaquemelo e @matheusgimenez acho necessária uma conversa para definirmos isso.

**Comment by willowmagrini** [comment]
Menu Home :
Precisa manter o sanduiche? (em termos de conteúdo) podemos esconder ele?
Logo vem pro meio e aumenta
Menu de editorias e busca vem pra linha de baixo e ocupa 100%

 Menu internas
menu institucional vem pra baixo
menu de editorias vai pro sanduiiche
logo centraliza

**Comment by isaquemelo** [comment]
Bem, vou primeiro minha opiniao como designer sobre o caso:

**Menu Home :**
Precisa manter o sanduiche? (em termos de conteúdo) podemos esconder ele?
me pediram para colocar varios menus no layout e foi o que eu fiz..  pensei em toda a organizacao geral do menu contando com esse elemento. Mas, se nao ha conteudo nao tem o que fazer, e um elemento a menos quando ja foi-se inserido outros elementos fora do padrao proposto nao deve ser julgado. 

**Logo vem pro meio e aumenta**
discordo em relacao d alinhamento e a um crescimento superior a 1/3 da atual, acho que o logo ja esta visível e esta cumprindo o seu papel corretamente. Qualquer crescimento exacerbado pode causar um desvio de atencao e foco indevido em um elemento.

**Menu de editorias e busca vem pra linha de baixo e ocupa 100%**
Ja pensaram como o alinhamento vai ornar com o geral dos blocos e a grid dos widgets? Vai ficar muito estranho, vai fugir completamente.. Vai ficar como se fosse uma parte "independente" do site. Pensem na home, por exemplo, com todos aqueles blocos.

**Menu internas**
**menu institucional vem pra baixo**
Esse elemento não parece ser de foco primario no site na entrada do usuario. Jogar o menu editorias para o sanduiche é um tiro no pé. O usuario vai ter que se esforçar muito para realizar uma ação simples. O proposito do hamburguer é guardar itens completamente fora do interesse primario do usuario.. UX e UI ficam prejudicados. 

Opinião como front-end:
O que o cliente fechar eu faço hahahaha
