### ISSUE TITLE
Footer geral

### ISSUE THREAD

**Issue by matheusgimenez** [brasadesign/esquerdaonline-theme#3]
![footer](https://user-images.githubusercontent.com/4724804/37071323-bf08ab8c-219a-11e8-860f-7772232fe6ce.png)

**Comment by matheusgimenez** [comment]
@isaquemelo Eu não to entendendo a divisão de colunas ai, são 7 no total, certo? qual o tamanho de cada uma?

**Comment by willowmagrini** [comment]
E a newsletter no footer?

**Comment by matheusgimenez** [comment]
Esse newsletter ta layoutado? não ne?
