### ISSUE TITLE
Single-noticia - sombra na imagem principal

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#31]
A sombra em degrade na imagem principal está indo até quase a metade da foto, isso esta atrapalhando a visualização de algumas imagens.

**Comment by isaquemelo** [comment]
O cliente especificou se é para remover tudo ou só reduzir a opacidade geral?

**Comment by willowmagrini** [comment]
diminuir a altura da sombra, Faz terminar em no maximo 1/4 da foto para vermos.
