### ISSUE TITLE
archive-colunistas - Título da página e do widget

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#34]
A repetição Colunistas no título e no widget ta estranha. Gostaria de sugestões para esses dois títulos.
@matheusgimenez, @LuwkasLima e @isaquemelo

**Comment by LuwkasLima** [comment]
@willowmagrini @willowmagrini onde ta o layout pra eu pensar?

**Comment by willowmagrini** [comment]
https://novodev.brasa.art.br/esquerdaonline/colunistas/

**Comment by willowmagrini** [comment]
e ai, nada aqui @LuwkasLima @matheusgimenez e @isaquemelo ?
que tal o título da página ser "Arquivo: colunistas'  o widget na barra lateral ser 'OutrXs'?

**Comment by LuwkasLima** [comment]
@willowmagrini Cara, nao eh bom usar "x" em sites por causa das ferramentas de leitura pra cegos

**Comment by willowmagrini** [comment]
Vamos com "índice colunistas" e "Acesso Rápido"
