### ISSUE TITLE
archive-colunistas - icones sociais

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#35]
Os nomes dos colunistas podem ser bem compridos (colunas duplas) talvez isso gere uma diferença grande no posicionamento dos sociais, vamos alinhar eles a direita e ver como fica.

**Comment by isaquemelo** [comment]
Tu diz deixar fixo à direita e o nome quebrar se acontecer de ultrapassar?

**Comment by willowmagrini** [comment]
sim, sociais na direita o nome segue alinhado na esquerda
