### ISSUE TITLE
Criar script para levar taxonomias para colunistas

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#45]
Criar script ou escolher plugin para transformar as antigas taxonomias em editorias.

**Comment by matheusgimenez** [comment]
Vai ter que ser na mão, não existe um padrão nos nomes.

**Comment by willowmagrini** [comment]
Criar na mao os CPTS de cada colunistas e depois fazer query com todas as categorias filhas da categoria colunista e adicionar o termo do respectivo colunista na noticia.

**Comment by matheusgimenez** [comment]
Feito!

O processo é o seguinte, cria os colunistas (eu posso fazer isso, desde que eu saiba quais vão ser mantidos), e roda a seguinte a página: https://esquerdaonline.com/migracao-colunistas/
