### ISSUE TITLE
Shortcode Matérias relacionadas

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#46]
Esse shortcode será uma lista das matérias relacionadas que foram escolhidas na edição do post.
@matheusgimenez faz ele criar a lista e deixa que o front eu resolvo ou passo pro diego.

**Comment by willowmagrini** [comment]
exemplo:
![captura de tela 2018-05-02 as 14 18 45](https://user-images.githubusercontent.com/8497431/39538624-c93e77d0-4e13-11e8-859a-57590690858b.png)

**Comment by willowmagrini** [comment]
A mesma classe utilizada pelo shortcode será utilizada pelo widget repetidor para exibir as relacionadas.

**Comment by matheusgimenez** [comment]
Ta feito essa funcionalidade. Qlq duvida de uso me deem um toque! :)

**Comment by matheusgimenez** [comment]
Ah, o nome do shortcode pra testar é [eol_relacionadas]

**Comment by willowmagrini** [comment]
La no novodev na hora de selecionar a matéria não aparecem os títulos.
