### ISSUE TITLE
Widget repetidor - Campos 

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#52]
Campos:
- Posição: Utilizar a taxonomia de organização para selecionar os posts. 
- Título do Widget
- Classes: controlam os elementos e estilos deles.
- Número de posts.

Observações:
 - Por padrão os campos exibidos são: Chapéu, Título, data e autor.  Os outros campos serão exibidos se as classes subtitulo e/ou resumo forem adicionadas ao campo classes.
 - As classes  100%, 66%, 50%, 33% e 25% irão definir o tamanho de cada elemento do widget  (cada notícia)
 - As classes foto-fundo, foto-esquerda, foto-meio e sem-foto irão determinar a posição da foto em relação ao texto.
- Classe exibir relacionadas

**Comment by willowmagrini** [comment]
O título está sendo exibido duas vezes.

**Comment by matheusgimenez** [comment]
Não to conseguindo reproduzir aqui.. que classes vc usou? abs!

**Comment by willowmagrini** [comment]
@matheusgimenez autor ainda repete...

**Comment by matheusgimenez** [comment]
@willowmagrini tirei a repetiçao de autor tbm
