### ISSUE TITLE
editorias - Áreas de widget

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#55]
Acho que o ideal é termos uma área de widget por archive de editoria.
Use a função myTheme_registerWidgetAreas que está na linha 559 do functions.php para criar uma área de Widget para cada archive de termo de editoria

**Comment by matheusgimenez** [comment]
Já tem, só precisa me falar onde vai ser exibido no caso da editoria

**Comment by willowmagrini** [comment]
No novodev segue uma área de widget comum entre todas as editorias.

**Comment by matheusgimenez** [comment]
@willowmagrini repito minha pergunta na issue.. existem duas areas widget no taxonomy-editorias.php, em qual delas vai ser aplicado o widget especifico de acordo com a editoria?

Abs!

**Comment by willowmagrini** [comment]
A área do topo é pra colocar o widget de destaques então pode ser a mesma para todos.
A barra lateral deve ser exclusiva e caso não tenha widgets nela  pega a geral (editorias-archive-sidebar)
