### ISSUE TITLE
Widgets - Widgets de compartilhar o site

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#59]
Um widget para ir na barra lateral com botão de compartilhamento nas redes sociais (mais padrão possivel)

**Comment by matheusgimenez** [comment]
Feito! :)

**Comment by matheusgimenez** [comment]
Exemplo: https://novodev.brasa.art.br/esquerdaonline/editorias/movimento/

**Comment by willowmagrini** [comment]
Ok, agora vou dar uma tapa no css disso.
