### ISSUE TITLE
Widget de redes sociais (novo)

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#72]
criar um widget com o campo classe do widget e campos para o preenchimento das redes sociais do EOL.
Ao clicar a pessoa vai para a página do EOL na rede social.
Se isso já existe me notifica aqui

**Comment by matheusgimenez** [comment]
Tá pelo customizer.

Minha sugestão é fazer um shortcode que cuspa isso ai.. ai da pra usar dentro de um widget de texto
