### ISSUE TITLE
single-noticia - intertítulo, <h3> com tratamento especial

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#8]
Configurar o “cabeçalho 3” do editor para exibir no front um íntertítulo ( gif do cursor piscando, fonte maior que o texto e pode ser colorida de acordo com a editoria)

Os textos dento da tag h3 nas singles devem servir como intertítulos. Acho que um padding e um estilo diferente na fonte talvez de conta.

Em https://novodev.brasa.art.br/esquerdaonline/2017/08/12/municiparios-de-porto-alegre-mobilizados-para-derrotar-marchezan/
a frase "A categoria promete parar Porto Alegre se o pacote que acaba com o plano se carreira não for retirado."

**Comment by isaquemelo** [comment]
@willowmagrini Não entendi mano

**Comment by willowmagrini** [comment]
a tag h3 será utilizada por eles para a criação de intertítulos.
o estilo do texto contido na tag h3 deve ser diferente, pode colocar um padding na esquerda e mudar um pouco o estilo da fonte (bold, tamanho maior etc). A parte do cursor piscando deixa pra mais tarde

**Comment by willowmagrini** [comment]
Lacrou
