### ISSUE TITLE
single-noticias - continue lendo

### ISSUE THREAD

**Issue by willowmagrini** [brasadesign/esquerdaonline-theme#9]
Configurar a seção “continue lendo” para funcionar através de afinidade de tags. Remover subtítulo e diminuir imagem.
Isso esta acontecendo dessa forma @matheusgimenez ? Posso marcar como feito?

**Comment by isaquemelo** [comment]
@willowmagrini sobre remover os subtitulos: não vejo o por que disso, o cliente falou algo? Por que tu achas que devemos remover o sub?

**Comment by willowmagrini** [comment]
Ele que falou, quer menos informação e a foto menor também.

**Comment by isaquemelo** [comment]
@willowmagrini Belezura

**Comment by isaquemelo** [comment]
@willowmagrini mano essa daqui ele só não quer descrição só na parte de continue lendo ou em todos(que se aplicam ao mesmo padrão, tipo no widget da home)?

**Comment by willowmagrini** [comment]
Ele havia dito no continue lendo. Vou confirmar.

**Comment by willowmagrini** [comment]
pode fazer @isaquemelo ele falou disso de novo na reunião. outra observação, não precisa diminuir a imagem, vamos manter o padrão de tamanho da home.
